INSERT INTO COVERS (ID,COVER_NAME) VALUE(2,"Land");
INSERT INTO COVERS (ID,COVER_NAME) VALUE(3,"Trees");
INSERT INTO COVERS (ID,COVER_NAME) VALUE(4,"Walls");
INSERT INTO COVERS (ID,COVER_NAME) VALUE(5,"Cart");
